name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      # Gradle
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle_version: current
      - name: Execute Gradle build
        run: ./gradlew build

#      - name: Upload test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: junit-tests-report
#          path: build/test-results/test