name: Build

on: push

jobs:
  gradle:
    uses: ./.github/workflows/gradle.yml
  junit:
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --warning-mode all
#      - name: Upload test report
#        uses: actions/upload-artifact@v3
#        with:
#          name: junit-tests-report
#          path: build/test-results/test