name: Checkstyle
on:
  workflow_call:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle.xml'
