name: Checkstyle
on:
  workflow_call:
    inputs:
      tests:
        required: true
        default: false
        type: boolean

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Run Checkstyle
        if: { { inputs.tests } } == false
        run: ./gradlew checkstyleMain
      - name: Run Checkstyle on tests
        if: { { inputs.tests } } == true
        run: ./gradlew checkstyleTest
      - uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: 'build/reports/checkstyle/main.xml'
