name: Spotbugs

on:
  workflow_call:

jobs:
  spotbugs:
    runs-on: ubuntu-latest
    steps:
      - uses: jwgmeligmeyling/spotbugs-github-action@v1.2
        with:
          path: '**/spotbugs/excludes.xml'