name: JUnit tests

on: push

jobs:
  junit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      # Gradle
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew test
      #      - name: Execute Gradle tests
      #        run: ./gradlew test -Pheadless
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'